version: '3.7'

services:
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-server
    ports:
      - 3001:3001
    volumes:
      - ./env/.env:/sns-service/env/.env
      - ./src:/sns-service/src
    restart: "always"

  database-server:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'wantedsns'
        MYSQL_ROOT_PASSWORD: '1234'
        MYSQL_TCP_PORT: 3307
        TZ: 'Asia/Seoul'
      ports:
        - 3307:3307