export const MSG = {
  createUser: { code: 201, msg: '회원가입 요청이 성공했습니다!' },
  getUser: { code: 200, msg: '유저 정보 조회에 성공했습니다!' },
  loginUser: { code: 200, msg: '유저 로그인 요청에 성공했습니다!' },
  logoutUser: { code: 200, msg: '유저 로그아웃 요청에 성공했습니다!' },
  verifyUser: { code: 200, msg: '유저 인증 성공에 성공했습니다!' },
  refreshTokenWithUser: { code: 200, msg: '유저 인증 성공에 성공했습니다!' },
  createArticle: { code: 201, msg: '게시물 생성에 성공하였습니다!' },
  getOneArticle: { code: 200, msg: '게시물 상세 요청에 성공하였습니다.' },
  getArticleList: { code: 200, msg: '게시물 목록 요청에 성공하였습니다.' },
  deleteArticle: { code: 200, msg: '게시물 삭제 요청에 성공하였습니다.' },
  restoreArticle: { code: 200, msg: '게시물 복구 요청에 성공하였습니다.' },
  updateArticle: { code: 200, msg: '게시물 수정을 성공하였습니다.' },
  likeArticle: { code: 201, msg: '게시물 좋아요 요청에 성공하였습니다.' },
  unlikeArticle: { code: 200, msg: '게시물 좋아요가 취소되었습니다.' },
  getUsersLike: { code: 200, msg: '게시물 좋아요 목록 요청에 성공하였습니다.' },
  createComment: { code: 201, msg: '게시물 댓글 생성 요청에 성공하였습니다.' },
  updateComment: { code: 200, msg: '게시물 댓글 수정 요청에 성공하였습니다.' },
  deleteComment: { code: 200, msg: '게시글 댓글 삭제 요청에 성공하였습니다.' },
};
